export const AGREGAR_PERSONAJE = 'AGREGAR_PERSONAJE';
export const AGREGAR_PERSONAJE_EXITO = 'AGREGAR_PERSONAJE_EXITO';
export const AGREGAR_PERSONAJE_ERROR = 'AGREGAR_PERSONAJE_ERROR';

export const CARGAR_PERSONAJES = 'CARGAR_PERSONAJES';
export const CARGAR_PERSONAJES_EXITO = 'CARGAR_PERSONAJES_EXITO';
export const CARGAR_PERSONAJES_ERROR = 'CARGAR_PERSONAJES_ERROR';

export const CARGAR_EPISODIOS = 'CARGAR_EPISODIOS';
export const CARGAR_EPISODIOS_EXITO = 'CARGAR_EPISODIOS_EXITO';
export const CARGAR_EPISODIOS_ERROR = 'CARGAR_EPISODIOS_ERROR';

